import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./Reuseable components/Sidebar";
import Footer from "./Reuseable components/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./Reuseable components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen">
          {/* Sidebar Section */}
          <div className="w-[25%] lg:w-[16%] text-white bg-[#7d250e] h-screen sticky top-0">
            <Sidebar />
          </div>
 <Navbar/> 
          {/* Main Content Section */}
          <div className="flex flex-col w-[75%] flex-grow bg-gray-100">
            <div className="flex-grow px-4 py-4">{children}</div>
            { <Footer />}
          </div>
        </div>
      </body>
    </html>
  );
}
